[workspace]
members = ["crates/*"]

[package]
name = "lanime"
version = "0.1.0"
edition = "2021"

[dependencies]
lanime_renderer = { path = "crates/lanime_renderer" }
lanime_curves = { path = "crates/lanime_curves" }
pollster = "0.3.0"
