[workspace]
members = ["crates/*"]

[package]
name = "lanime"
version = "0.1.0"
edition = "2021"

[dependencies]
lanime_animation = { path = "crates/lanime_animation" }
lanime_renderer = { path = "crates/lanime_renderer" }
pollster = "0.3.0"
