[package]
name = "lanime_nodes"
version = "0.1.0"
edition = "2021"

[dependencies]
lanime_core = { path = "../lanime_core" }
lanime_bindfields = { path = "../lanime_bindfields" }
lanime_renderer = { path = "../lanime_renderer" }
wgpu_text = "0.6.7"
